// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppjjqvaubgcnnymeciak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwampxdmF1Ymdjbm55bWVjaWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTIwOTQsImV4cCI6MjA1NDA4ODA5NH0.Y-H8xO-JIIMHWwPJRGUWz7ZKa-hxtvxGWqSzJVhCqJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);